### ISSUE TITLE
direct upload of nodes JSON-data

### ISSUE THREAD

**Issue by SvenRoederer** [freifunk-berlin/hopglass.berlin.freifunk.net#11]
Even hopglass was intentionally planned as an additional map to OWM, it has now become the main-map for us as OWM has died.

Currently the node-data gets uploaded to the utils.berlin.freifunk.net server which has forwarded them to OWM and hopglass. As currently no (full-featured) alternative to the former OWM seems on the way, I wonder:

**Should we think of a more effective way to handle this data?**
* There are some ideas of replacing the OWM toolset (https://github.com/freifunk-berlin/firmware/issues/819)
* There are some open issues with the owm-tool on the nodes (https://github.com/freifunk-berlin/firmware/issues/763, https://github.com/freifunk-berlin/firmware/issues/778)

I'm asking, because I found some things in the owm-client, which makes me think of rewriting / replacing the whole tool.

**Comment by sarumpaet** [comment]
My plan was to write a proper replacement for the OWM backend in Python+Postgres at some point.

The current "backend" is just a small PHP script that dumps the incoming OWM JSON data to disk to be read by the Hopglass converter later. It doesn't provide any query endpoints (that the old OWM backend provided), so some functionality on the website and in the wiki doesn't work anymore.

However, writing that new backend should be about one day of work, and we need it anyway as replacing the whole thing won't make all those OWM client nodes go away (and might well introduce another API that _will_ be legacy at some point).

**Comment by SvenRoederer** [comment]
> My plan was to write a proper replacement for the OWM backend in Python+Postgres at some point.
> 

"plan was" or "plan is"?

> However, writing that new backend should be about one day of work, and we need it anyway as replacing the whole thing won't make all those OWM client nodes go away (and might well introduce another API that _will_ be legacy at some point).

A good argument for staying with the current JSON-API for publishing the data we currently do already (generic node data) and probably do more processing on the server-side.

---

One part of the "some things in the owm-client" was the idea of integrating the node-monitoring (see https://github.com/freifunk-berlin/firmware/issues/819#issuecomment-654511579). For this I send a request for comments to the Mailinglist (https://lists.berlin.freifunk.net/pipermail/berlin/2020-December/051852.html)

**Comment by sarumpaet** [comment]
> "plan was" or "plan is"?

Good question! I don't really know. If someone else wants to help with it or do it altogether, go at it.

**Comment by sarumpaet** [comment]
OWM is back: 898e5179dcea2e1fb7469fb1b886eace16e12a26
