### ISSUE TITLE
Decrease time for considering node online

### ISSUE THREAD

**Issue by akira25** [freifunk-berlin/hopglass.berlin.freifunk.net#15]
Currently hopglass considers a node sent it''s last hello-message more than 20 hours ago as online. I agree that this is a point of how we define online, but I think that we should decrease that time to maybe two hours.

Here's a picture of the situation in that I got known of this issue. The link between fffw-schloss and fffw-wr1043-test already deceased, but fffw-schoss is still considered online. That's somehow confusing.

![image](https://user-images.githubusercontent.com/43141307/121501410-83240d00-c9df-11eb-8e4c-93c4c2b0fb5e.png)

**Comment by akira25** [comment]
In addition, we deliver the statistics via HTTP over TCP. So we could safely assume, that a node isn't online anymore, if we didn't hear from it for 2 hours.

**Comment by sarumpaet** [comment]
I just tested this - reducing the time to two hours marks 21 additional nodes as offline currently. Apparently quite a few nodes are somewhat unstable. 🙈
Done in c7c3fa2

**Comment by akira25** [comment]
Thank you a lot for that qick fix! :)
