### ISSUE TITLE
Definition of "routeronly" and "hotspot" in .nodes[].nodeinfo.system.site_code

### ISSUE THREAD

**Issue by adam-burns** [freifunk-berlin/hopglass.berlin.freifunk.net#19]
I'm looking at filtering https://hopglass.berlin.freifunk.net/nodes.json for only .nodeinfo entries that offer public connection to the freifunk network over wifi.

I note the "routeronly" and "hotspot" values of .nodes[].nodeinfo.system.site_code, is this helpful?

Or does this distinguish independent ISP backhaul from FF backbone backhaul?

Thanks!

**Comment by adam-burns** [comment]
Seems to be set here in [owm2ffmap.py](https://github.com/freifunk-berlin/hopglass.berlin.freifunk.net/blob/c7c3fa218789dfeb67dd9a5251d44ea3141d6237/owm2ffmap/owm2ffmap.py#L207-L236)

**Comment by pktpls** [comment]
We've not really made use of that category for a while, but my understanding is that "hotspot" is supposed to be a site that provides wifi to a public place, i.e. more than just a small wifi bubble in a flat. Something that you see on the map, go there, and actually get working internet.

I'd like that distinction to become more visible in the future.

**Comment by SvenRoederer** [comment]
Indeed it provides at least the network-interface which is dedicated for enduser-clients. But there is no guarantee that a Wifi interface is present / Wifi is available to the public (e.g. 20th level of a building). It can also be just a ethernet-cable ...

But I this the site-code is the best you can get. More detailed data you should be able to get directly from the [OWM-Server](https://github.com/freifunk/openwifimap-api) to make up your own way of determining public-wifi state. Data are feed to the server via https://github.com/freifunk/openwrt-packages/blob/master/applications/luci-app-owm/luasrc/owm.lua.

**Comment by adam-burns** [comment]
Thank you @pktpls & @SvenRoederer for your responses & explanations!
 
( Just FYI: I'm looking at an experimental meaningful subset of nodeinfo data of the FF Berlin db to import into dynamic secure DNS (starting with geodata using DNS LOC records). Another part of this experiment also allows each node to 'own' their own dynamic DNS subdomain, holding their own cryptographic keypairs to update their own local info. Details such as geolocation and service discovery can be autonomously updated by the node itself directly into the DNS fabric. We gave a presentation of this project at a Freifunk monthly meetup @ c-base some months back. )

**Comment by adam-burns** [comment]
The Presentation of the work-in-progress [sig0namectl](https://sig0namectl.networkcommons.org/) project at the May Freifunk Berlin meeting can be found [here](https://github.com/NetworkCommons/sig0namectl/blob/master/presentations/20240501%20Freifunk%20Berlin%20May%20meeting%20Presentation.pdf).
