### ISSUE TITLE
wrong uplink-detection on Hedy-based releases

### ISSUE THREAD

**Issue by bobster-galore** [freifunk-berlin/hopglass.berlin.freifunk.net#2]
Hej,

how will we detect an uplink from Hedy on?
There will be no more ffvpn as checked here https://github.com/freifunk-berlin/hopglass.berlin.freifunk.net/blob/master/owm2ffmap/owm2ffmap.py#L137 
Will checking for ffuplink be sufficient or do mesh-only router also have that interface? @SvenRoederer 

ru b

**Comment by SvenRoederer** [comment]
referencing this from hopglass -> statistics?

![hopglass_uplink](https://user-images.githubusercontent.com/1755362/37832805-f9ff2286-2ea9-11e8-9298-21ffdf024711.PNG)

**Comment by bobster-galore** [comment]
Yes.
The two are direct upgrades I think, they feature ffuplink as well as ffvpn. 
Earlier I installed a mesh-only router, which also has an ffuplink interface, so this isn't the ultimate distinction.
router w uplink {"ifname":"ffuplink","up":"1","device":"ffuplink","neighbors":...
router w/o uplink {"ifname":"ffuplink","neighbors":...
So we might check for string: "device":"ffuplink" to check for uplinks on Hedy.

**Comment by SvenRoederer** [comment]
Seems that this have been fixed by PR #8
