### ISSUE TITLE
Using "scriptname" of node to show up as firmware-version

### ISSUE THREAD

**Issue by SvenRoederer** [freifunk-berlin/hopglass.berlin.freifunk.net#3]
In 656adb6a89e9e0a568ef37fb941d4c4ead96c8cb the code was changed to use the "scriptname" of the nodeinfo to show up as firmware-version as last resort.

https://github.com/freifunk-berlin/hopglass.berlin.freifunk.net/blob/656adb6a89e9e0a568ef37fb941d4c4ead96c8cb/owm2ffmap/owm2ffmap.py#L212

![Screenshot_20200101_220427](https://user-images.githubusercontent.com/1755362/71646170-da4e8a00-2ce3-11ea-85bc-5600176670b8.png)

This datafield shows up in the "Firmwareversion" section, but what tells the script used about the firmware it is running on?
I prefer to change it back to "depecated", probably with the scriptname in the current "Revision-field". This will end up in something like "Deprecated / freifunk-olsrd" in the Firmware-line of a node info.

**Comment by sarumpaet** [comment]
This was done because at 36c3 we wondered what all those "unknown" firmware versions in the statistic were about. It'd be nice to keep the script info in the aggregated stats; perhaps make `release` something like "unknown (scriptname)"?
